liubrandon/pod_6

gregg/README.md

Updated Gregg's README

---

gregg/README.md
gregg/first_python_challenge.py

I am attempting to merge my branch to the main branch

Gregg's First Python Challenge

---

gregg/README.md
gregg/first_python_challenge.py
kelvin/README.md

adding a .git_ignore file

---

gregg/temperature.py

Converting Temperatures

---

raya/temperature.py

Here is my temperature calculation script
Thanks Brandon, 
Raya

Adding Temeperature Calculations Mooo

---

Kelvin/nba_challenge.py
README.md
kelvin/README.md
kelvin/temperature.py

Nba challenge.py

---

kelvin/box_office_challenge.py
kelvin/restaurants_challenge.py
kelvin/snippets_challenge.py
kelvin/stock_challenge.py
kelvin/temperature.py

Restaurant challenge.py

---

gregg/restaurants_challenge.py

Gregg Restaurant Challenge

---

gregg/buy_me_a_laptop_challenge.py

Greggs Laptop Challenge

---

raya/nba_challenge.py
raya/stocks.py

Are you able to view my nba_challenge?
Thanks Brandon
Raya

Challenge 3

---

raya/nba_challenge.py
raya/stocks.py
raya/temperature.py

Here is the update to my NBA_Challenge.. idk why my \ for a new line kept causing an error in the code to cancel the entire print out, it would not read the entire string even if I had it on one line.
Raya

Nba challenge raya

---

raya/nba_challenge.py
raya/snippet.py
raya/stocks.py
raya/temperature.py

Here is the update to my Snippets_Challenge
Raya

Snippet challenge

---

raya/nba_challenge.py
raya/snippet.py
raya/stocks.py
raya/temperature.py

Here is my Stocks_Challenge.
Raya

Stocks challenge

---

raya/box_challenge.py
raya/nba_challenge.py
raya/snippet.py
raya/stocks.py
raya/temperature.py

Here is my box_challege script!
Thank you Brandon.
Raya

Box challenge

---

gregg/library_challenge.py

This was very challenging and I feel like I don't fully understand the the final part of the code. Please let me know if there is a better way to write the code or if what I did was the best way to go about it.

Gregg's Library Challenge

---

Kelvin/nba_challenge.py
kelvin/bootcamp_1.py
kelvin/box_office_challenge.py
kelvin/buy_me_a_laptop_challenge.py
kelvin/first_python_challenge.py
kelvin/restaurants_challenge.py
kelvin/snippets_challenge.py
kelvin/stocks_challenge.py

It took me this long, but I DID IT>

Stocks challenge.py

---

gregg/playlist_challenge.py
gregg/playlist_functions.py

I will see you on Saturday for OH because the answer to the Bonus makes no sense to me lol

Gregg's Playlist Challenge

---

gregg/index.html
gregg/styles.css

I am just not sure about centering the images. Most resources showed I should use .center but I was able to do it without that. Could be luck not sure.

Gregg's HTML/CSS

---

raya/book_challenge.py
raya/book_class.py
raya/exceptions_challenge.py
raya/playlist_challenge.py
raya/playlist_functions.py

Here is my OOP Challenge !
Lemme know.
Safe vacay Brandon!
**Raya**

OOOP_Class_Creation_Challenge_15rayaMooo

---

raya/playlist_challenge.py
raya/playlist_functions.py

Any comments, lemme know.
Thanks Brandon,
**Raya**

Challenge twelve_Importing_raya

---

raya/exceptions_challenge.py
raya/playlist_challenge.py
raya/playlist_functions.py

Any questions lemme know.
**Raya**

Challenge thirteen
